### PR TITLE
Block local network

### LINKED ISSUE #81: Add support for redirect-gateway block-local
OpenVPN supports the `redirect-gateway` value `block-local`:

> block-local  -- Block access to local LAN when the tunnel is active, except for the LAN gateway itself.  This is accomplished by routing the local LAN (except for the LAN gateway address) into the tunnel.

The idea is to avoid the "local" attack vector where devices on the LAN can connect to the iOS device. I am not sure this is a real threat on iOS? Maybe a firewall on the device takes care of this, or maybe iOS doesn't allow you to block "(W)LAN" traffic...

### PR DESCRIPTION
**Pull request by keeshux**
Partially fixes #81. Blocks outgoing traffic, yet unexplicably lets other hosts in the LAN reach the client. 

Better said, it's normal that the host is reachable one-way, it's not normal that the host e.g. responds to a ping.

### CODE REVIEW

**Comment by keeshux** [comment]
@fkooman I'm afraid I can't do more than this. Also, OpenVPN Connect doesn't seem to support it at all.

**Comment by fkooman** [comment]
Thanks! I was gonna test it on OpenVPN Connect next, but I guess you already did. Thanks! :)

**Comment by keeshux** [comment]
Are you able to review/test this PR? Otherwise I'll merge it regardless, even if half-working it's an optional feature.

**Comment by fkooman** [comment]
If there is a TestFlight build yes, if not, I am not able to build this myself, my Mac died.

**Comment by keeshux** [comment]
Passepartout Beta 1845.

**Pull request merged**
